config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'

  resources :users do
    resources :photos
    collection do
      get '/emails', to: 'users#emails', as: 'emails'
    end
  end

  resources :photos do
    member do
      get 'comments', to: 'photos#comments', as: 'comments'
    end
  end
  
  resources :comments, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy]

  get '/log-in' => "sessions#new"
  post '/log-in' => "sessions#create"
  get '/log-out' => "sessions#destroy", as: :log_out
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user

  validates :text , presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/photo.rb
class Photo<ActiveRecord::Base
  belongs_to :user
  has_many :tags, dependent: :destroy
  has_many :comments, dependent: :destroy
  

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :title, presence: true
end

app/models/tag.rb
class Tag<ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos
  has_many :tags
  has_many :comments
  attr_accessor :password
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_confirmation_of :password
  before_save :encrypt_password
  validates :email, uniqueness: true
  validates :email, presence: true

  has_many :follows, foreign_key: :follower_id, dependent: :destroy
  has_many :followed_users, through: :follows, source: :followed

  has_many :reverse_follows, foreign_key: :followed_id, class_name: 'Follow', dependent: :destroy
  has_many :followers, through: :reverse_follows, source: :follower

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def is_email?
    self.email.include?('@') && self.email.include?('.')
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @photo = Photo.find(params[:comment][:photo_id])
    @comment = @photo.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      render json: {
        html: render_to_string(partial: 'users/comments', locals: { photo: @photo, comments: @photo.comments.includes(:user) }, formats: [:html]),
        text: @comment.text
      }, status: :created
    else
      render json: { errors: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end


  def destroy
    @comment = Comment.find(params[:id])
    @photo = @comment.photo
    if @comment.user == current_user || @photo.user == current_user
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to request.referrer, notice: 'Comment was successfully deleted.' }
        format.json { head :no_content }
      end
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:text, :photo_id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    Follow.create(follower_id: current_user.id, followed_id: user.id)
    flash[:notice] = "You are now following #{user.email}"
    redirect_to :back
  end

  def destroy
    follow = Follow.find(params[:id])
    follow.destroy
    flash[:notice] = "You have unfollowed #{follow.followed.email}"
    redirect_to :back
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    if params[:photo].nil?
      flash[:alert] = "Please upload a photo"
      redirect_back(fallback_location: user_path(@user))
    else
      @photo = Photo.create(photo_params)
      @photo.user_id = @user.id
      @photo.save
      flash[:notice] = "Successfully uploaded a photo"
      redirect_to user_path(@user)
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @photo = Photo.create()
  end
  
  def destroy
    @photo = Photo.find(params[:id])
    if @photo.user == current_user
      @photo.destroy
      flash[:notice] = "Photo and its associated comments and tags deleted successfully."
    else
      flash[:alert] = "You can only delete your own photos."
    end
    redirect_to :back
  end


  def comments
    @photo = Photo.find(params[:id])
    @comments = @photo.comments.includes(:user)
    render json: 'users/comments', locals: { photo: @photo, comments: @comments } 
  end

 

  private

  def photo_params
    params.require(:photo).permit(:image, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem logging you in!"
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/tags_controller.rb
class TagsController<ActionController::Base
  def new
    redirect_to "/"
  end

  def create
    @user = User.find(params[:tag][:user_id])
    @tag = Tag.create({user_id: params[:tag][:user_id], photo_id: params[:tag][:photo_id]})
    redirect_to user_path(session[:user_id])
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    @user.valid?
    if !@user.is_email?
      flash[:alert] = "Input a properly formatted email."
      redirect_back(fallback_location: root_path)
    elsif @user.errors.messages[:email].present?
      flash[:notice] = "That email " + @user.errors.messages[:email].first
      redirect_back(fallback_location: root_path)
    elsif @user.save
      flash[:notice] = "Signup successful. Welcome to the site!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_back(fallback_location: root_path)
    end
  end

  def new
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @tag = Tag.new
    @photos = @user.photos.order(created_at: :desc)
    @comment = Comment.new
    @followed_users = @user.followed_users.includes(:photos)
    @followed_photos = Photo.joins(user: :followers)
                            .where(follows: { follower_id: current_user.id })
                            .order(created_at: :desc)
                            .distinct
                            .includes(:comments)
    
  end

  def emails
    @users = User.all
    @current_user_email = params[:current_user_email]
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Treegram
%h2 Your Favorite Tree Photosharing Service
.row
  .col-sm-4
    = link_to 'Login', log_in_path, class: ["btn", "btn-success", 'btn-lg']
    = link_to 'Sign Up', new_user_path, class: ['btn', 'btn-success', 'btn-lg']
  .col-sm-7
    = image_tag "background.jpg"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PhotoShare
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = flash[:alert]
      = flash[:notice]
      = yield

app/views/photos/new.html.haml
%h1 Add a Photo
= form_for Photo.new(), :url => user_photos_path, :html => {:multipart => true} do |form|
  = form.file_field :image
  = form.label :title, 'Give a title: '
  = form.text_field :title
  = form.submit 'Upload'

app/views/photos/show.html.haml
= image_tag @photo.image.url
= image_tag @photo.image.url(:thumb)

app/views/users/_comments.html.haml
%h3
  %strong
    %u Comments

- comments.each do |comment|
  %p
    - if comment.user
      %strong= comment.user.email
      %br/
      = comment.text
      - if comment.user == current_user || photo.user == current_user
        = button_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?', comment_id: comment.id }, class: 'btn btn-danger btn-sm delete-comment', style: 'display: inline; margin-left: 10px;'


= form_for Comment.new, url: comments_path, remote: true, html: { class: 'new_comment', id: 'comment-form' } do |f|
  = f.hidden_field :photo_id, value: photo.id
  .form-group
    = f.label :text, 'Add a comment:'
    = f.text_area :text, class: 'form-control', rows: 1
    = f.submit 'Post Comment', class: 'btn btn-primary'

app/views/users/emails.html.haml
%h1{ style: "text-align: center; font-size: 50px;" } Registered Users

%ul{ style: "text-align: left; font-size: 25px;" }
  - @users.each do |user|
    %ul{ style: "display: flex; align-items: center; justify-content: center; margin-bottom: 10px;" }
      %span{ style: "flex: 1;" }= user.email
      - if user.email == @current_user_email
        %span{ style: "font-size: 25px; color: green; margin-left: 20px;" } Active user
      - else
        - if Follow.exists?(follower_id: current_user.id, followed_id: user.id)
          = button_to 'Following', follow_path(Follow.find_by(follower_id: current_user.id, followed_id: user.id)), method: :delete, class: ['btn', 'btn-secondary'], style: 'margin-left: 20px;'
        - else
          = button_to 'Follow', follows_path(followed_id: user.id), method: :post, class: ['btn', 'btn-primary'], style: 'margin-left: 20px;'
%br/
%br/
.row
  .col-sm-12
    = link_to 'Back to Main Page', user_path(current_user), class: ['btn', 'btn-danger'], style: 'margin: 50 auto; text-align: center;'

app/views/users/new.html.haml
%h1 Sign Up
= form_for User.new, class: "form-inline" do |f|
  = f.label :email
  = f.text_field :email
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  %br/
  = f.label :avatar, 'Upload Avatar'
  = f.file_field :avatar
  %br/
  = f.submit "Sign Up"

app/views/users/show.html.haml
.row.top_row
  .col-sm-6.user_att
    %h2= @user.email
    - if @user.avatar_file_name
      = image_tag @user.avatar.url(:thumb)
  .col-sm-4
    = link_to 'Registered Users', emails_users_path(current_user_email: @user.email), class: ['btn', 'btn-info', 'users_btn']
  .col-sm-6
    = link_to 'Logout', log_out_path, class: ['btn', 'btn-danger', 'logout_btn']
.row
  = link_to 'Add Photo', new_user_photo_path(@user), class: ['btn', 'btn-success', 'add_photo_btn']
%br/
%br/
%br/
%br/
%br/
%br/
%br/
%br/
%br/
%br/
%div#current-user-photos
  %h1{ style: "text-align: center; font-size: 50px;" } My photos
  .photo-container{ style: "display: flex; flex-wrap: wrap;" }
    - if @photos.any?
      - recent_photo = @photos.first
      .slideshow-container{ data: { user_id: @current_user.id } }
        %img{ src: recent_photo.image.url(:medium), alt: recent_photo.title, class: "photo-click", data: { photo_id: recent_photo.id, url: comments_photo_path(recent_photo), user_email: @current_user.email  } }
        .photo{ style: "display: none; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: white; z-index: 10;" }
          - @current_user.photos.order(created_at: :desc).each_with_index do |photo, index|
            .slide{ style: "display:none" }
              %img{ src: photo.image.url(:medium), alt: photo.title, style: "width:100%", class: "photo-click recent-user-photo", data: { photo_id: photo.id, url: comments_photo_path(photo), user_email: @current_user.email  } }
              %div.caption{style: "text-align: center; font-size: 20px;"}= photo.title
    
    - else
      %p No photos to display.
%br/
%br/
%br/
%div{ style: "margin-top: 50px;" }
  %h1{ style: "text-align: center; font-size: 50px;" } Photos of Followed Users
  .photos-container{ style: "display: flex; flex-wrap: wrap;" }
    - @followed_users.order(created_at: :desc).each do |followed_user|
      %div{ style: "margin-right: 20px;" }
        %h2{ style: "text-align: center;" }= followed_user.email
        - if followed_user.photos.any?
          - recent_photo = followed_user.photos.order(created_at: :desc).first
          .slideshow-container{ data: { user_id: followed_user.id } }
            %img{ src: recent_photo.image.url(:medium), alt: recent_photo.title, class: "photo-click", data: { photo_id: recent_photo.id, url: comments_photo_path(recent_photo), user_email: followed_user.email } }
            .photo{ style: "display: none; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: white; z-index: 10;" }
              - followed_user.photos.order(created_at: :desc).each_with_index do |photo, index|
                .slide{ style: "display:none" }
                  %img{ src: photo.image.url(:medium), alt: photo.title, style: "width:100%", class: "photo-click", data: { photo_id: photo.id, url: comments_photo_path(photo), user_email: followed_user.email } }
                  %div.caption{style: "text-align: center; font-size: 20px;"}= photo.title
        - else
          %p No photos to display.
       

.logged-in-as
  - if @current_user_email
    %ul{ style: "text-align: right; font-size: 25px;" }
      %li
        Logged in as
        = @current_user_email
#comments-popup{ style: "display: none; position: fixed; top: 10%; left: 10%; width: 80%; height: 80%; background: rgba(0, 0, 0, 0.8); color: white; z-index: 20; overflow: auto;" }
  .popup-header{ style: "position: relative; padding: 10px;" }
    %h5{ style: "margin: 0;" } Photo Comments
    %button#close-comments &times;
  - @photos.each do |photo|
    - if photo.present?
      #comments-container
        = render partial: 'users/comments', locals: { photo: photo, comments: photo.comments.includes(:user) }
    - else
      %p No comments to display.